import { notFound } from 'next/navigation';
import Link from 'next/link';
import ProductDetail from '@/components/product/ProductDetail';
import ProductGrid from '@/components/product/ProductGrid';

// Placeholder for when API is unavailable
const MOCK_PRODUCTS = {
  'chicken-harvest': {
    id: '1',
    name: 'Chicken Harvest',
    slug: 'chicken-harvest',
    badge: 'Best Seller',
    dogType: 'Active & Everyday Pups',
    proteinType: 'Chicken (Single Source)',
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Chicken Gizzard • Pumpkin • Carrot • Peas • Sweet Potato',
    shortDescription: 'Wholesome nutrition with real chicken, pumpkin & garden veggies.',
    description: 'A vibrant, complete meal made with high-protein fresh chicken, pumpkin, sweet potatoes, and farm-fresh carrots. Packed with wholesome nutrition and zero artificial preservatives to keep your dog energized and thriving.',
    keyBenefits: ['Real chicken as #1 ingredient', 'Complete & balanced nutrition', 'Pumpkin for healthy digestion', '100% human-grade ingredients', 'Zero artificial preservatives'],
    ingredients: 'Fresh Chicken, Pumpkin, Sweet Potato, Carrots, Peas, Brown Rice, Flaxseed Oil, Essential Vitamins & Chelated Minerals.',
    nutritionalInfo: { energy: '110 kcal/100g', crudeProtein: '10%', crudeFat: '5%', crudeFiber: '1.5%', moisture: '78%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days to help your pet adjust to the new food.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds & Sizes',
    isVeg: false,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken Harvest' }],
    variants: [
      { id: 'v1-1', name: '1 Pouch (100g)', count: 1, mrp: 219, sellingPrice: 199, stockQuantity: 100 },
      { id: 'v1-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1533, sellingPrice: 1249, stockQuantity: 100 },
      { id: 'v1-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3285, sellingPrice: 2499, stockQuantity: 100 },
      { id: 'v1-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6570, sellingPrice: 4479, stockQuantity: 100 },
    ],
  },
  'chicken-homestyle': {
    id: '2',
    name: 'Chicken Homestyle',
    slug: 'chicken-homestyle',
    badge: 'Classic Comfort',
    dogType: 'Sensitive Stomach Pups',
    proteinType: 'Chicken & Rice',
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Rice • Pumpkin • Carrot • Peas • Sweet Potato',
    shortDescription: 'Homestyle slow-cooked chicken with rice, peas & pumpkin.',
    description: 'Inspired by comforting home-cooked meals, Chicken Homestyle combines tender shredded chicken with soft-steamed brown rice, tender green peas, and golden pumpkin. Gentle on the stomach and loved by picky eaters.',
    keyBenefits: ['Gentle on sensitive tummies', 'Lean, bioavailable chicken protein', 'High fiber for digestive regularity', 'Human-grade ingredients', 'Zero fillers or preservatives'],
    ingredients: 'Chicken, Steamed Brown Rice, Green Peas, Pumpkin, Carrots, Cold-Pressed Coconut Oil, Mineral & Vitamin Blend.',
    nutritionalInfo: { energy: '108 kcal/100g', crudeProtein: '9.5%', crudeFat: '4.8%', crudeFiber: '1.8%', moisture: '77%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds & Sizes',
    isVeg: false,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/chicken-homestyle-front.jpg', altText: 'Chicken Homestyle' }],
    variants: [
      { id: 'v2-1', name: '1 Pouch (100g)', count: 1, mrp: 219, sellingPrice: 199, stockQuantity: 100 },
      { id: 'v2-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1533, sellingPrice: 1249, stockQuantity: 100 },
      { id: 'v2-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3285, sellingPrice: 2499, stockQuantity: 100 },
      { id: 'v2-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6570, sellingPrice: 4479, stockQuantity: 100 },
    ],
  },
  'golden-egg-quinoa': {
    id: '3',
    name: 'Golden Egg & Quinoa',
    slug: 'golden-egg-quinoa',
    badge: 'Superfood',
    dogType: 'High Energy & Active Pups',
    proteinType: 'Farm Egg & Quinoa',
    highlightIngredients: 'Egg • Quinoa • Sweet Potato • Pumpkin • Carrot • Spinach • Green Peas • Zucchini',
    shortDescription: 'Farm-fresh eggs with superfood quinoa & pumpkin for active pups.',
    description: 'A protein-rich vegetarian power bowl combining farm-fresh whole eggs with ancient quinoa, fiber-dense pumpkin, and crisp zucchini. An optimal amino acid profile that builds lean muscle and supports sustained play.',
    keyBenefits: ['Complete amino acid profile from farm eggs', 'Antioxidant-rich quinoa superfood', 'Supports active energy & stamina', 'Omega-3 fatty acids for coat shine', '100% human-grade ingredients'],
    ingredients: 'Whole Farm-Fresh Eggs, Ancient Quinoa, Pumpkin, Zucchini, Chia Seeds, Spinach, Flaxseed, Calcium & Trace Minerals.',
    nutritionalInfo: { energy: '115 kcal/100g', crudeProtein: '11%', crudeFat: '6%', crudeFiber: '2%', moisture: '75%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds & Sizes',
    isVeg: true,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/golden-egg-quinoa-front.jpg', altText: 'Golden Egg & Quinoa' }],
    variants: [
      { id: 'v3-1', name: '1 Pouch (100g)', count: 1, mrp: 209, sellingPrice: 189, stockQuantity: 100 },
      { id: 'v3-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1463, sellingPrice: 1199, stockQuantity: 100 },
      { id: 'v3-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3135, sellingPrice: 2399, stockQuantity: 100 },
      { id: 'v3-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6270, sellingPrice: 4299, stockQuantity: 100 },
    ],
  },
  'paneer-greens': {
    id: '4',
    name: 'Paneer & Greens',
    slug: 'paneer-greens',
    badge: '100% Veg',
    dogType: 'Vegetarian Households',
    proteinType: 'Fresh Paneer (100% Veg)',
    highlightIngredients: 'Paneer • Rice • Pumpkin • Carrot • Green Peas • Spinach • Chia Seeds',
    shortDescription: 'Fresh paneer cubes with spinach, carrots & green beans.',
    description: 'A delicious vegetarian recipe featuring premium paneer cubes rich in calcium and clean protein, gently tossed with tender spinach, garden green beans, and sweet carrots. Crafted for optimal gut health and glowing coats.',
    keyBenefits: ['Fresh paneer rich in natural calcium', 'Antioxidant greens (spinach & beans)', 'Supports gut health & smooth digestion', 'Ideal for meat-sensitive dogs', 'Zero preservatives or artificial colors'],
    ingredients: 'Fresh Paneer (Cottage Cheese), Baby Spinach, Green Beans, Carrots, Brown Rice, Turmeric, Cold-Pressed Flaxseed Oil, Vitamins & Minerals.',
    nutritionalInfo: { energy: '112 kcal/100g', crudeProtein: '9%', crudeFat: '6.5%', crudeFiber: '2.2%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds & Sizes',
    isVeg: true,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/paneer-greens-front.jpg', altText: 'Paneer & Greens' }],
    variants: [
      { id: 'v4-1', name: '1 Pouch (100g)', count: 1, mrp: 209, sellingPrice: 189, stockQuantity: 100 },
      { id: 'v4-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1463, sellingPrice: 1199, stockQuantity: 100 },
      { id: 'v4-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3135, sellingPrice: 2399, stockQuantity: 100 },
      { id: 'v4-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6270, sellingPrice: 4299, stockQuantity: 100 },
    ],
  },
  'lamb-lentil-harvest': {
    id: '5',
    name: 'Lamb Lentil Harvest',
    slug: 'lamb-lentil-harvest',
    badge: 'High Protein',
    dogType: 'Pickiest Eaters & Muscle Building',
    proteinType: 'Pasture Lamb & Lentils',
    highlightIngredients: 'Lean Lamb • Lamb Liver • Red Lentils • Sweet Potato • Carrot • Green Beans • Broccoli • Cauliflower',
    shortDescription: 'Hearty slow-cooked lamb with red lentils, sweet potato & broccoli.',
    description: 'A nutrient-dense gourmet feast featuring succulent, slow-cooked lamb paired with hearty lentils, vitamin-rich sweet potatoes, and fresh broccoli. Packed with bioavailable iron, zinc, and B-vitamins to build strength and fuel vitality.',
    keyBenefits: ['Rich red meat protein from tender lamb', 'Iron and B-vitamins for stamina', 'Dietary fiber from hearty lentils', 'Supports joint mobility & strength', 'No artificial additives or preservatives'],
    ingredients: 'Fresh Lamb, Red Lentils, Sweet Potato, Broccoli, Green Peas, Sunflower Oil, Rosemary Extract, Essential Vitamins & Chelated Minerals.',
    nutritionalInfo: { energy: '122 kcal/100g', crudeProtein: '12%', crudeFat: '7%', crudeFiber: '1.6%', moisture: '74%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Adult & Senior Dogs – All Breeds',
    isVeg: false,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb Lentil Harvest' }],
    variants: [
      { id: 'v5-1', name: '1 Pouch (100g)', count: 1, mrp: 249, sellingPrice: 229, stockQuantity: 100 },
      { id: 'v5-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1743, sellingPrice: 1449, stockQuantity: 100 },
      { id: 'v5-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3735, sellingPrice: 2899, stockQuantity: 100 },
      { id: 'v5-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 7470, sellingPrice: 5149, stockQuantity: 100 },
    ],
  },
  // ─── 5 Official Recipes ───
  'chicken-vegetables': {
    id: 'chicken-vegetables',
    name: 'Chicken & Vegetables Wet Dog Food',
    slug: 'chicken-vegetables',
    shortDescription: 'A nutritious wet dog food made with whole chicken, chicken liver, heart and gizzard, combined with pumpkin, carrot, peas and sweet potato.',
    description: 'A nutritious wet dog food made with whole chicken, chicken liver, heart and gizzard, combined with pumpkin, carrot, peas and sweet potato for a wholesome everyday meal.',
    badge: 'Best Seller',
    dogType: 'Active & Everyday Pups',
    proteinType: 'Chicken (Single Source)',
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Chicken Gizzard • Pumpkin • Carrot • Peas • Sweet Potato',
    keyBenefits: ['Whole chicken as #1 ingredient', 'Rich in natural organ meats (liver, heart, gizzard)', 'Pumpkin & sweet potato for gentle digestion', '100% human-grade ingredients', 'Zero artificial preservatives'],
    ingredients: 'Whole Chicken, Chicken Liver, Chicken Heart, Chicken Gizzard, Pumpkin, Carrot, Peas, Sweet Potato, Cold-Pressed Flaxseed Oil, Essential Vitamins & Minerals.',
    nutritionalInfo: { energy: '112 kcal/100g', crudeProtein: '10.5%', crudeFat: '5.2%', crudeFiber: '1.4%', moisture: '77%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days to help your pet adjust to the new food.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds & Sizes',
    isVeg: false,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables Wet Dog Food' }],
    variants: [
      { id: 'v-cv-1', name: '1 Pouch (100g)', count: 1, mrp: 219, sellingPrice: 199, stockQuantity: 100 },
      { id: 'v-cv-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1533, sellingPrice: 1249, stockQuantity: 100 },
      { id: 'v-cv-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3285, sellingPrice: 2499, stockQuantity: 100 },
      { id: 'v-cv-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6570, sellingPrice: 4479, stockQuantity: 100 },
    ],
  },
  'chicken-rice-vegetables': {
    id: 'chicken-rice-vegetables',
    name: 'Chicken Rice & Vegetables Wet Dog Food',
    slug: 'chicken-rice-vegetables',
    shortDescription: 'A wholesome chicken and rice wet dog food made with whole chicken, chicken liver and heart, along with pumpkin, carrot, peas and sweet potato.',
    description: 'A wholesome chicken and rice wet dog food made with whole chicken, chicken liver and heart, along with pumpkin, carrot, peas and sweet potato.',
    badge: 'Classic Comfort',
    dogType: 'Sensitive Stomach Pups',
    proteinType: 'Chicken & Rice',
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Rice • Pumpkin • Carrot • Peas • Sweet Potato',
    keyBenefits: ['Gentle on delicate stomachs', 'Wholesome rice for easily digestible energy', 'Chicken organ meats for vital nutrients', 'Carrot and pumpkin for gut motility', 'Zero fillers or chemical stabilizers'],
    ingredients: 'Whole Chicken, Chicken Liver, Chicken Heart, Rice, Pumpkin, Carrot, Peas, Sweet Potato, Cold-Pressed Flaxseed Oil, Essential Minerals.',
    nutritionalInfo: { energy: '110 kcal/100g', crudeProtein: '9.8%', crudeFat: '4.8%', crudeFiber: '1.5%', moisture: '78%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Puppy & Adult Dogs – Especially Sensitive Stomachs',
    isVeg: false,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/chicken-homestyle-front.jpg', altText: 'Chicken Rice & Vegetables Wet Dog Food' }],
    variants: [
      { id: 'v-crv-1', name: '1 Pouch (100g)', count: 1, mrp: 219, sellingPrice: 199, stockQuantity: 100 },
      { id: 'v-crv-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1533, sellingPrice: 1249, stockQuantity: 100 },
      { id: 'v-crv-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3285, sellingPrice: 2499, stockQuantity: 100 },
      { id: 'v-crv-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6570, sellingPrice: 4479, stockQuantity: 100 },
    ],
  },
  'egg-superfood': {
    id: 'egg-superfood',
    name: 'Egg Superfood Wet Dog Food with Quinoa & Vegetables',
    slug: 'egg-superfood',
    shortDescription: 'A nutrient-packed egg wet dog food combining egg and quinoa with sweet potato, pumpkin, spinach, carrots, green peas and zucchini.',
    description: 'A nutrient-packed egg wet dog food combining egg and quinoa with sweet potato, pumpkin, spinach, carrots, green peas and zucchini for a delicious meal.',
    badge: 'Superfood',
    dogType: 'High Energy & Active Pups',
    proteinType: 'Farm Egg & Quinoa',
    highlightIngredients: 'Egg • Quinoa • Sweet Potato • Pumpkin • Carrot • Spinach • Green Peas • Zucchini',
    keyBenefits: ['Complete amino acid profile from farm eggs', 'Organic quinoa for sustained play stamina', 'Spinach, zucchini and pumpkin for antioxidants', 'Omega fatty acids for shiny coat', '100% human-grade ingredients'],
    ingredients: 'Egg, Quinoa, Sweet Potato, Pumpkin, Carrot, Spinach, Green Peas, Zucchini, Chia Seeds, Flaxseed Oil, Essential Vitamins.',
    nutritionalInfo: { energy: '115 kcal/100g', crudeProtein: '11%', crudeFat: '6%', crudeFiber: '2%', moisture: '75%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: true,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/golden-egg-quinoa-front.jpg', altText: 'Egg Superfood Wet Dog Food' }],
    variants: [
      { id: 'v-es-1', name: '1 Pouch (100g)', count: 1, mrp: 209, sellingPrice: 189, stockQuantity: 100 },
      { id: 'v-es-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1463, sellingPrice: 1199, stockQuantity: 100 },
      { id: 'v-es-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3135, sellingPrice: 2399, stockQuantity: 100 },
      { id: 'v-es-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6270, sellingPrice: 4299, stockQuantity: 100 },
    ],
  },
  'paneer-vegetables': {
    id: 'paneer-vegetables',
    name: 'Paneer & Vegetables Wet Dog Food',
    slug: 'paneer-vegetables',
    shortDescription: 'A wholesome vegetarian wet dog food made with paneer, rice and nutritious vegetables including pumpkin, carrot, green peas and spinach.',
    description: 'A wholesome vegetarian wet dog food made with paneer, rice and nutritious vegetables including pumpkin, carrot, green peas and spinach.',
    badge: '100% Veg',
    dogType: 'Vegetarian Households',
    proteinType: 'Fresh Paneer (100% Veg)',
    highlightIngredients: 'Paneer • Rice • Pumpkin • Carrot • Green Peas • Spinach • Chia Seeds',
    keyBenefits: ['Fresh paneer rich in natural calcium and protein', 'Chia seeds for digestive lubricity and Omega-3', 'Nutrient-dense spinach and carrots', 'Ideal for vegetarian households & sensitive pups', 'Zero artificial colors, flavors or preservatives'],
    ingredients: 'Paneer, Rice, Pumpkin, Carrot, Green Peas, Spinach, Chia Seeds, Cold-Pressed Coconut Oil, Mineral & Vitamin Blend.',
    nutritionalInfo: { energy: '114 kcal/100g', crudeProtein: '9.5%', crudeFat: '6.5%', crudeFiber: '2%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: true,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/paneer-greens-front.jpg', altText: 'Paneer & Vegetables Wet Dog Food' }],
    variants: [
      { id: 'v-pv-1', name: '1 Pouch (100g)', count: 1, mrp: 209, sellingPrice: 189, stockQuantity: 100 },
      { id: 'v-pv-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1463, sellingPrice: 1199, stockQuantity: 100 },
      { id: 'v-pv-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3135, sellingPrice: 2399, stockQuantity: 100 },
      { id: 'v-pv-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 6270, sellingPrice: 4299, stockQuantity: 100 },
    ],
  },
  'lamb-lentils': {
    id: 'lamb-lentils',
    name: 'Lamb & Lentils Wet Dog Food with Vegetables',
    slug: 'lamb-lentils',
    shortDescription: 'A hearty lamb wet dog food made with lean lamb meat and lamb liver, combined with red lentils, sweet potato and wholesome vegetables.',
    description: 'A hearty lamb wet dog food made with lean lamb meat and lamb liver, combined with red lentils, sweet potato and wholesome vegetables.',
    badge: 'High Protein',
    dogType: 'Pickiest Eaters & Muscle Building',
    proteinType: 'Pasture Lamb & Lentils',
    highlightIngredients: 'Lean Lamb • Lamb Liver • Red Lentils • Sweet Potato • Carrot • Green Beans • Broccoli • Cauliflower',
    keyBenefits: ['Lean pasture lamb & nutrient-rich lamb liver', 'Red lentils for gentle soluble fiber', 'Broccoli, cauliflower and green beans for antioxidants', 'Naturally hypoallergenic red meat source', 'Zero rendered meat meals'],
    ingredients: 'Lean Lamb, Lamb Liver, Red Lentils, Sweet Potato, Carrot, Green Beans, Broccoli, Cauliflower, Sunflower Oil, Chelated Minerals.',
    nutritionalInfo: { energy: '122 kcal/100g', crudeProtein: '12%', crudeFat: '7%', crudeFiber: '1.6%', moisture: '74%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce FurBowl gradually over 7 days.',
    suitableFor: 'Adult & Senior Dogs – Especially Picky Eaters',
    isVeg: false,
    foodType: 'WET',
    category: { name: 'Meals', slug: 'meals' },
    images: [{ url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils Wet Dog Food' }],
    variants: [
      { id: 'v-ll-1', name: '1 Pouch (100g)', count: 1, mrp: 249, sellingPrice: 229, stockQuantity: 100 },
      { id: 'v-ll-7', name: '7-Pack Box', count: 7, badge: 'Save 12%', subtitle: '1-Week Fresh Plan', mrp: 1743, sellingPrice: 1449, stockQuantity: 100 },
      { id: 'v-ll-15', name: '15-Pack Box', count: 15, badge: 'Save 20%', subtitle: 'Half-Month Supply', mrp: 3735, sellingPrice: 2899, stockQuantity: 100 },
      { id: 'v-ll-30', name: '30-Pack Box', count: 30, badge: 'Save 25% • Best Value', subtitle: 'Monthly Fresh Diet', mrp: 7470, sellingPrice: 5149, stockQuantity: 100 },
    ],
  },

  // ─── Curated Trial Packs ───
  'all-recipes-trial-pack': {
    id: 'all-recipes-trial-pack',
    name: 'All Recipes Wet Dog Food Trial Pack – 5 x 100g',
    slug: 'all-recipes-trial-pack',
    shortDescription: '1 of each recipe (Chicken, Lamb, Egg & Paneer). ⭐ Best first-time discovery pack.',
    description: 'The ultimate tasting discovery pack for first-time FurBowl pups! Contains 1 pouch of all 5 chef-crafted recipes: Chicken & Vegetables, Chicken Rice & Vegetables, Egg Superfood with Quinoa, Paneer & Vegetables, and Lamb & Lentils.',
    badge: '⭐ Best First Purchase',
    tagline: '5 Flavours • 1 of Each Recipe',
    packCount: 5,
    totalWeight: '500g (5 x 100g Pouches)',
    purpose: 'Best first-time discovery pack for pups to taste every single recipe.',
    packIngredients: 'Chicken • Lamb • Egg • Paneer • Pumpkin • Carrot',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 1 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 1 },
    ],
    keyBenefits: ['1 of each recipe included (5 total pouches)', 'Find your dog’s favorite flavor effortlessly', '100% human-grade whole food ingredients', 'Vacuum-sealed freshness with cold delivery', '100% money-back taste guarantee'],
    ingredients: 'Chicken, Lamb, Egg, Paneer, Pumpkin, Carrot, Sweet Potato, Green Peas, Rice, Quinoa, Spinach, Broccoli, Lentils.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.5% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Feed 1 pouch daily to explore different flavor preferences.',
    suitableFor: 'All Breeds & Life Stages',
    isVeg: false,
    foodType: 'TRIAL_PACK',
    category: { name: 'Trial Packs', slug: 'trial-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-all-three.jpg', altText: 'All Recipes Wet Dog Food Trial Pack' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
      { url: '/images/products/golden-egg-quinoa-front.jpg', altText: 'Egg Superfood' },
      { url: '/images/products/paneer-greens-front.jpg', altText: 'Paneer & Vegetables' },
    ],
    variants: [{ id: 'v-tp-5', name: '5 x 100g Pack', mrp: 599, sellingPrice: 499, stockQuantity: 100 }],
  },
  'chicken-lovers-trial-pack': {
    id: 'chicken-lovers-trial-pack',
    name: 'Chicken Wet Dog Food Trial Pack – 4 x 100g',
    slug: 'chicken-lovers-trial-pack',
    shortDescription: '2x Chicken & Vegetables + 2x Chicken Rice with Vegetables. For poultry lovers.',
    description: 'Designed specifically for dogs who adore classic chicken flavours. Contains 2 pouches of Chicken & Vegetables and 2 pouches of Chicken Rice with Vegetables.',
    badge: 'Chicken Lovers',
    tagline: '2 Chicken Veg + 2 Chicken Rice',
    packCount: 4,
    totalWeight: '400g (4 x 100g Pouches)',
    purpose: 'For dogs who prefer classic, irresistible poultry flavours.',
    packIngredients: 'Whole Chicken • Chicken Liver • Pumpkin • Carrot • Green Peas',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 2 },
    ],
    keyBenefits: ['2x Chicken & Veg + 2x Chicken Rice', 'Real chicken meat & organ meats', 'Packed with pumpkin, carrots and peas', 'High digestibility protein', 'Gentle on stomachs'],
    ingredients: 'Whole Chicken, Chicken Liver, Chicken Heart, Rice, Pumpkin, Carrot, Green Peas, Sweet Potato.',
    nutritionalInfo: { energy: '110 kcal/100g', crudeProtein: '10%', crudeFat: '5%', crudeFiber: '1.5%', moisture: '77%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce over 7 days.',
    suitableFor: 'All Breeds & Life Stages',
    isVeg: false,
    foodType: 'TRIAL_PACK',
    category: { name: 'Trial Packs', slug: 'trial-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-chicken.jpg', altText: 'Chicken Wet Dog Food Trial Pack' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/chicken-homestyle-front.jpg', altText: 'Chicken Rice & Vegetables' },
    ],
    variants: [{ id: 'v-tp-4c', name: '4 x 100g Pack', mrp: 479, sellingPrice: 399, stockQuantity: 100 }],
  },
  'meat-lovers-trial-pack': {
    id: 'meat-lovers-trial-pack',
    name: 'Chicken & Lamb Wet Dog Food Trial Pack – 4 x 100g',
    slug: 'meat-lovers-trial-pack',
    shortDescription: '1x Chicken & Veg + 1x Chicken Rice + 2x Lamb & Lentils. Protein-focused.',
    description: 'A protein-focused power pack pairing succulent chicken with rich pasture lamb and red lentils. Ideal for active dogs and muscle maintenance.',
    badge: 'Meat-Focused',
    tagline: '1 Chicken Veg + 1 Chicken Rice + 2 Lamb',
    packCount: 4,
    totalWeight: '400g (4 x 100g Pouches)',
    purpose: 'Chicken + lamb combination; more protein-focused positioning.',
    packIngredients: 'Chicken • Lamb • Liver • Pumpkin • Carrot • Red Lentils',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 1 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 2 },
    ],
    keyBenefits: ['1x Chicken Veg, 1x Chicken Rice, 2x Lamb & Lentils', 'High protein red and white meat duo', 'Nutrient-rich liver for natural vitamins', 'Supports stamina and agility', 'Zero meal or byproducts'],
    ingredients: 'Chicken, Lamb, Liver, Pumpkin, Carrot, Red Lentils, Green Peas, Sweet Potato.',
    nutritionalInfo: { energy: '118 kcal/100g', crudeProtein: '11.5%', crudeFat: '6.2%', crudeFiber: '1.5%', moisture: '75%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce over 7 days.',
    suitableFor: 'Adult & Active Dogs',
    isVeg: false,
    foodType: 'TRIAL_PACK',
    category: { name: 'Trial Packs', slug: 'trial-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-lamb.jpg', altText: 'Chicken & Lamb Wet Dog Food Trial Pack' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
    ],
    variants: [{ id: 'v-tp-4cl', name: '4 x 100g Pack', mrp: 519, sellingPrice: 429, stockQuantity: 100 }],
  },
  'chicken-egg-trial-pack': {
    id: 'chicken-egg-trial-pack',
    name: 'Chicken & Egg Wet Dog Food Trial Pack – 4 x 100g',
    slug: 'chicken-egg-trial-pack',
    shortDescription: '1x Chicken & Veg + 1x Chicken Rice + 2x Egg SuperFood with Quinoa.',
    description: 'Combines comforting chicken recipes with farm-fresh egg and superfood quinoa for optimal coat health and muscle repair.',
    badge: 'Familiar + Variety',
    tagline: '1 Chicken Veg + 1 Chicken Rice + 2 Egg',
    packCount: 4,
    totalWeight: '400g (4 x 100g Pouches)',
    purpose: 'Familiar chicken flavours with superfood egg for variety.',
    packIngredients: 'Chicken • Egg • Pumpkin • Carrot • Green Peas • Quinoa',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 1 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 2 },
    ],
    keyBenefits: ['1x Chicken Veg, 1x Chicken Rice, 2x Egg SuperFood', 'Egg choline and Omega fatty acids for fur shine', 'Quinoa complex carbohydrates for sustained energy', 'Gentle on stomachs', 'Zero preservatives'],
    ingredients: 'Chicken, Egg, Pumpkin, Carrot, Green Peas, Quinoa, Spinach, Sweet Potato.',
    nutritionalInfo: { energy: '112 kcal/100g', crudeProtein: '10.5%', crudeFat: '5.5%', crudeFiber: '1.8%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce over 7 days.',
    suitableFor: 'Puppy & Adult Dogs',
    isVeg: false,
    foodType: 'TRIAL_PACK',
    category: { name: 'Trial Packs', slug: 'trial-packs' },
    images: [
      { url: '/images/products/golden-egg-quinoa-front.jpg', altText: 'Chicken & Egg Wet Dog Food Trial Pack' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/chicken-homestyle-front.jpg', altText: 'Chicken Rice & Vegetables' },
    ],
    variants: [{ id: 'v-tp-4ce', name: '4 x 100g Pack', mrp: 479, sellingPrice: 399, stockQuantity: 100 }],
  },
  'meat-veggie-variety-pack': {
    id: 'meat-veggie-variety-pack',
    name: 'Meat & Veggie Wet Dog Food Trial Pack – 6 x 100g',
    slug: 'meat-veggie-variety-pack',
    shortDescription: '2x Chicken Veg + 1x Chicken Rice + 1x Lamb + 1x Egg + 1x Paneer.',
    description: 'Our most comprehensive tasting pack featuring 6 pouches. Includes an extra pouch of our bestselling Chicken & Vegetables alongside Lamb, Egg, Paneer, and Chicken Rice.',
    badge: 'Ultimate Variety',
    tagline: '2 Chicken Veg + 1 Chicken Rice + 1 Lamb + 1 Egg + 1 Paneer',
    packCount: 6,
    totalWeight: '600g (6 x 100g Pouches)',
    purpose: 'Complete tasting selection with an extra serving of our #1 Chicken meal.',
    packIngredients: 'Chicken • Lamb • Egg • Paneer • Pumpkin • Carrot',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
    ],
    keyBenefits: ['6 pouches total: 2x Chicken Veg + 1 of each other flavor', 'Complete variety across all poultry, meat & veg proteins', 'High bioavailability and 100% human-grade whole foods', 'Ideal for multifold taste exploration', 'Vacuum sealed freshness'],
    ingredients: 'Chicken, Lamb, Egg, Paneer, Pumpkin, Carrot, Sweet Potato, Peas, Rice, Quinoa, Spinach.',
    nutritionalInfo: { energy: '112–122 kcal/100g', crudeProtein: '9.5% – 12%', crudeFat: '5% – 7%', crudeFiber: '1.6%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Introduce over 7 days.',
    suitableFor: 'All Breeds & Life Stages',
    isVeg: false,
    foodType: 'TRIAL_PACK',
    category: { name: 'Trial Packs', slug: 'trial-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-all-three.jpg', altText: 'Meat & Veggie Wet Dog Food Trial Pack' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
      { url: '/images/products/paneer-greens-front.jpg', altText: 'Paneer & Vegetables' },
    ],
    variants: [{ id: 'v-tp-6mv', name: '6 x 100g Pack', mrp: 699, sellingPrice: 579, stockQuantity: 100 }],
  },
  'all-recipes-7-pack': {
    id: 'all-recipes-7-pack',
    name: 'Pack of 7 – All Recipes 1-Week Plan',
    slug: 'plan-pack-of-7',
    shortDescription: '1-Week Fresh Feeding Plan with Chicken, Lamb, Egg & Paneer recipes.',
    description: 'A complete 7-day fresh food rotation designed to provide daily variety, balanced nutrition, and easy transition to fresh feeding. Includes 2x Chicken & Vegetables, 2x Chicken Rice, 1x Lamb & Lentils, 1x Egg Superfood, and 1x Paneer & Vegetables.',
    badge: '1-Week Plan',
    tagline: '7 Fresh Pouches • 1-Week Rotational Plan',
    packCount: 7,
    totalWeight: '700g (7 x 100g Pouches)',
    purpose: 'A complete weekly rotational diet for balanced vitality.',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 2 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
    ],
    keyBenefits: ['Complete 7-day weekly feeding plan', 'Balanced rotation across 4 unique protein sources', '100% human-grade whole food ingredients', 'Vacuum-sealed freshness for daily convenience', 'Zero artificial colors, fillers or preservatives'],
    ingredients: 'Whole Chicken, Chicken Liver, Lamb, Farm Eggs, Fresh Paneer, Pumpkin, Carrots, Sweet Potato, Quinoa, Peas, Cold-Pressed Oils, Essential Vitamins & Minerals.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.8% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Feed 1 pouch daily to complete a wholesome weekly rotation.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-chicken.jpg', altText: 'Pack of 7 Fresh Dog Food' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
    ],
    variants: [{ id: 'v-mp-7', name: 'Pack of 7 (7 x 100g)', mrp: 839, sellingPrice: 699, stockQuantity: 100 }],
  },
  'plan-pack-of-7': {
    id: 'plan-pack-of-7',
    name: 'Pack of 7 – 1-Week Starter Plan',
    slug: 'plan-pack-of-7',
    shortDescription: '7 × 100g • 1-Week Starter Plan with balanced rotation of fresh dog food.',
    description: 'A complete 7-day fresh food rotation designed to provide daily variety, balanced nutrition, and easy transition to fresh feeding. Includes 2x Chicken & Vegetables, 2x Chicken Rice, 1x Lamb & Lentils, 1x Egg Superfood, and 1x Paneer & Vegetables.',
    badge: '17% OFF • 1-Week Plan',
    tagline: '7 Fresh Pouches • 1-Week Rotational Plan',
    packCount: 7,
    totalWeight: '700g (7 x 100g Pouches)',
    purpose: 'A complete weekly rotational diet for balanced vitality.',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 2 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
    ],
    keyBenefits: ['Complete 7-day weekly feeding plan', 'Balanced rotation across 4 unique protein sources', '100% human-grade whole food ingredients', 'Vacuum-sealed freshness for daily convenience', 'Zero artificial colors, fillers or preservatives'],
    ingredients: 'Whole Chicken, Chicken Liver, Lamb, Farm Eggs, Fresh Paneer, Pumpkin, Carrots, Sweet Potato, Quinoa, Peas, Cold-Pressed Oils, Essential Vitamins & Minerals.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.8% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Feed 1 pouch daily to complete a wholesome weekly rotation.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-chicken.jpg', altText: 'Pack of 7 Fresh Dog Food' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
    ],
    variants: [{ id: 'v-mp-7', name: 'Pack of 7 (7 x 100g)', mrp: 839, sellingPrice: 699, stockQuantity: 100 }],
  },
  'plan-pack-of-14': {
    id: 'plan-pack-of-14',
    name: 'Pack of 14 – 2-Week Routine Plan',
    slug: 'plan-pack-of-14',
    shortDescription: '14 × 100g • 2-Week Routine Plan. Noticeable boost in coat shine & energy.',
    description: 'Two full weeks of balanced, rotational fresh meals crafted to build healthy gut flora, optimize digestion, and elevate your dog’s natural energy levels. Includes 4x Chicken & Vegetables, 4x Chicken Rice, 2x Lamb & Lentils, 2x Egg Superfood, and 2x Paneer Medley.',
    badge: '20% OFF • SUPER SAVER',
    tagline: '14 Fresh Pouches • 2-Week Fresh Plan',
    packCount: 14,
    totalWeight: '1.4kg (14 x 100g Pouches)',
    purpose: 'Two weeks of rotating human-grade nutrition for peak digestive performance.',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 4 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 4 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 2 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 2 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 2 },
    ],
    keyBenefits: ['14 daily fresh vacuum-sealed meals', 'Super saver pricing (20% OFF)', 'Rotational variety prevents picky eating habits', 'Shinier coat, smaller firm stools within 14 days', 'Zero fillers, wheat, soy or preservatives'],
    ingredients: 'Fresh Chicken, Chicken Liver, Lean Lamb, Farm Eggs, Fresh Paneer, Pumpkin, Carrots, Sweet Potato, Quinoa, Peas, Cold-Pressed Flaxseed & Coconut Oils.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.8% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Feed 1 pouch daily at breakfast or dinner.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-all-three.jpg', altText: 'Pack of 14 Fresh Dog Food' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
      { url: '/images/products/paneer-greens-front.jpg', altText: 'Paneer & Vegetables' },
    ],
    variants: [{ id: 'v-mp-14', name: 'Pack of 14 (14 x 100g)', mrp: 1679, sellingPrice: 1349, stockQuantity: 100 }],
  },
  'plan-pack-of-21': {
    id: 'plan-pack-of-21',
    name: 'Pack of 21 – 3-Week Habit Plan',
    slug: 'plan-pack-of-21',
    shortDescription: '21 × 100g • 3-Week Habit Plan. Form deep digestive health and clean stools.',
    description: 'A comprehensive 21-day fresh meal supply that solidifies healthy eating habits and supports long-term canine vitality. Packed with all 5 recipes for an irresistible, diverse daily bowl.',
    badge: '22% OFF • 3-Week Plan',
    tagline: '21 Fresh Pouches • 3-Week Habit Plan',
    packCount: 21,
    totalWeight: '2.1kg (21 x 100g Pouches)',
    purpose: '21 days of rotating fresh superfoods for sustained immunity and clean vitality.',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 6 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 6 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 3 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 3 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 3 },
    ],
    keyBenefits: ['21 fresh meals covering 3 full weeks', 'Substantial 22% discount against single pouches', 'Clinically supported rotation of clean protein & antioxidants', 'Gently cooked to preserve natural vitamins & enzymes', '100% human-grade guarantee'],
    ingredients: 'Whole Chicken, Chicken Liver, Lamb, Farm Eggs, Fresh Paneer, Pumpkin, Carrots, Sweet Potato, Quinoa, Peas, Cold-Pressed Oils, Essential Vitamins & Minerals.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.8% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Feed 1 pouch daily.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-lamb.jpg', altText: 'Pack of 21 Fresh Dog Food' },
      { url: '/images/products/bundles/furbowl-bundle-all-three.jpg', altText: 'All Recipes Multi-Pack' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
    ],
    variants: [{ id: 'v-mp-21', name: 'Pack of 21 (21 x 100g)', mrp: 2519, sellingPrice: 1949, stockQuantity: 100 }],
  },
  'plan-pack-of-28': {
    id: 'plan-pack-of-28',
    name: 'Pack of 28 – 4-Week Complete Month Plan',
    slug: 'plan-pack-of-28',
    shortDescription: '28 × 100g • 4-Week Complete Month Plan. Full 28-day fresh diet supply (Best Value).',
    description: 'Our flagship 28-day full month fresh food subscription box. 28 daily pouches offering the ultimate balance of chicken, lamb, egg, and paneer superfoods at our deepest 25% discount.',
    badge: '25% OFF • SUPER SAVER',
    tagline: '28 Fresh Pouches • 4-Week Full Diet',
    packCount: 28,
    totalWeight: '2.8kg (28 x 100g Pouches)',
    purpose: 'Complete 28-day fresh feeding diet delivered with max savings.',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 8 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 8 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 4 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 4 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 4 },
    ],
    keyBenefits: ['28 daily pouches for a complete 4-week monthly supply', 'Deepest savings bundle (25% OFF)', 'Rotational diet across poultry, meat, egg and vegetarian superfoods', 'Delivered fresh in cold insulated packaging', 'Highest rated customer favorite plan'],
    ingredients: 'Whole Chicken, Chicken Liver, Lamb, Farm Eggs, Fresh Paneer, Pumpkin, Carrots, Sweet Potato, Brown Rice, Quinoa, Spinach, Green Peas, Essential Vitamins & Chelated Minerals.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.5% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Feed 1 pouch daily.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [
      { url: '/images/products/bundles/bundle-all-three.jpg', altText: 'Pack of 28 Fresh Dog Food' },
      { url: '/images/products/bundles/furbowl-bundle-all-three.jpg', altText: 'All Recipes Multi-Pack' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
    ],
    variants: [{ id: 'v-mp-28', name: 'Pack of 28 (28 x 100g)', mrp: 3359, sellingPrice: 2499, stockQuantity: 100 }],
  },
  'plan-pack-of-10': {
    id: 'plan-pack-of-10',
    name: 'Pack of 10 – Bi-Weekly Stock Up',
    slug: 'plan-pack-of-10',
    shortDescription: '10 × 100g • 10-Pack Box with Chicken, Lamb, Egg & Paneer.',
    description: 'A convenient 10-pack box containing 10 vacuum-sealed 100g pouches of wholesome fresh dog food across all FurBowl recipes.',
    badge: '15% OFF',
    packCount: 10,
    totalWeight: '1kg (10 x 100g Pouches)',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 3 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice', count: 3 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 2 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
    ],
    keyBenefits: ['10 daily fresh meals', '15% discount', 'Convenient bi-weekly stock up'],
    ingredients: 'Chicken, Lamb, Egg, Paneer, Pumpkin, Carrot, Sweet Potato, Peas.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.8% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    suitableFor: 'All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [{ url: '/images/products/bundles/furbowl-bundle-all-three.jpg', altText: 'Pack of 10' }],
    variants: [{ id: 'v-mp-10', name: 'Pack of 10 (10 x 100g)', mrp: 1249, sellingPrice: 999, stockQuantity: 100 }],
  },
  'plan-pack-of-15': {
    id: 'plan-pack-of-15',
    name: 'Pack of 15 – Half-Month Fresh Diet',
    slug: 'plan-pack-of-15',
    shortDescription: '15 × 100g • Half-month supply of fresh wholesome dog food.',
    description: 'A 15-pack box providing half a month of clean, fresh daily meals.',
    badge: '20% OFF',
    packCount: 15,
    totalWeight: '1.5kg (15 x 100g Pouches)',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 5 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice', count: 4 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 2 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 2 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 2 },
    ],
    keyBenefits: ['15 daily meals', '20% discount', 'Complete 15-day rotation'],
    ingredients: 'Chicken, Lamb, Egg, Paneer, Pumpkin, Carrot, Sweet Potato, Peas.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.8% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    suitableFor: 'All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [{ url: '/images/products/bundles/furbowl-bundle-lamb.jpg', altText: 'Pack of 15' }],
    variants: [{ id: 'v-mp-15', name: 'Pack of 15 (15 x 100g)', mrp: 1799, sellingPrice: 1449, stockQuantity: 100 }],
  },
  'all-recipes-monthly-pack': {
    id: 'all-recipes-monthly-pack',
    name: 'All Recipes Dog Food Monthly Pack – 30 x 100g',
    slug: 'all-recipes-monthly-pack',
    shortDescription: 'Monthly full-diet subscription box with all 5 recipes (30 x 100g).',
    description: 'Our highest value monthly fresh meal box containing 30 daily vacuum-sealed pouches. Crafted with all 5 FurBowl recipes for complete nutritional variety throughout the month.',
    badge: 'Monthly Best Value',
    tagline: '30 Fresh Pouches • Full Month Nutrition Plan',
    packCount: 30,
    totalWeight: '3kg (30 x 100g Pouches)',
    purpose: 'Complete month-long fresh feeding diet delivered with max savings.',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 10 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 6 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 6 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 4 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 4 },
    ],
    keyBenefits: ['30 daily fresh pouches for a full month of feeding', 'Highest savings bundle (25% OFF)', 'Rotational diet across poultry, meat, egg and vegetarian superfoods', 'Delivered in cold insulated packaging', 'Cancel or pause anytime with peace of mind'],
    ingredients: 'Whole Chicken, Chicken Liver, Lamb, Farm Eggs, Fresh Paneer, Pumpkin, Carrots, Sweet Potato, Brown Rice, Quinoa, Spinach, Green Peas, Essential Vitamins & Chelated Minerals.',
    nutritionalInfo: { energy: '110–122 kcal/100g', crudeProtein: '9.5% – 12%', crudeFat: '4.8% – 7%', crudeFiber: '1.5%', moisture: '76%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '1/2 – 1 pack' },
      { weight: '5 – 15 kg', daily: '1 – 1.5 packs' },
      { weight: '15 – 30 kg', daily: '1.5 – 2 packs' },
      { weight: '30 kg & above', daily: '2.5 – 3.5 packs' },
    ],
    dietChangeGuide: 'Feed 1 pouch daily for standard adult dogs.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds',
    isVeg: false,
    foodType: 'MULTI_PACK',
    category: { name: 'Multi-Packs', slug: 'multi-packs' },
    images: [
      { url: '/images/products/bundles/furbowl-bundle-all-three.jpg', altText: 'All Recipes Dog Food Monthly Pack' },
      { url: '/images/products/chicken-harvest-front.jpg', altText: 'Chicken & Vegetables' },
      { url: '/images/products/lamb-lentil-harvest-front.jpg', altText: 'Lamb & Lentils' },
      { url: '/images/products/paneer-greens-front.jpg', altText: 'Paneer & Vegetables' },
    ],
    variants: [{ id: 'v-mp-30', name: '30 x 100g Pack', mrp: 3599, sellingPrice: 2699, stockQuantity: 100 }],
  },
  // ─── Bone Broth ───
  'golden-chicken-broth': {
    id: 'golden-chicken-broth',
    name: 'Golden Chicken Broth',
    slug: 'golden-chicken-broth',
    shortDescription: 'Warm, nourishing bone broth for hydration, digestion & joint care.',
    description: 'A slow-simmered golden bone broth crafted from free-range chicken bones, rich in natural collagen, glucosamine, and chondroitin. Perfect as a daily topper, hydration boost, or meal enhancer for picky eaters. 100% natural — no salt, no onion, no garlic.',
    keyBenefits: ['Natural collagen for joint health & mobility', 'Glucosamine & chondroitin for cartilage support', 'Boosts hydration in dry-food fed dogs', 'Gentle on sensitive stomachs', 'Zero salt, onion, garlic or additives'],
    ingredients: 'Free-Range Chicken Bones, Filtered Water, Apple Cider Vinegar (trace). Nothing else.',
    nutritionalInfo: { energy: '12 kcal/100ml', crudeProtein: '1.8%', crudeFat: '0.3%', crudeFiber: '0%', moisture: '98%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '30 – 50 ml/day' },
      { weight: '5 – 15 kg', daily: '50 – 100 ml/day' },
      { weight: '15 – 30 kg', daily: '100 – 150 ml/day' },
      { weight: '30 kg & above', daily: '150 – 200 ml/day' },
    ],
    dietChangeGuide: 'Can be served warm or at room temperature. Pour over kibble or fresh food, or serve alone.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds & Sizes',
    isVeg: false,
    foodType: 'BROTH',
    category: { name: 'Broth', slug: 'broth' },
    images: [{ url: '/images/products/golden-chicken-broth-front.jpg', altText: 'Golden Chicken Broth' }],
    variants: [{ id: 'v-gcb', name: '250ml Pouch', mrp: 149, sellingPrice: 129, stockQuantity: 100 }],
  },
  'slow-cooked-bone-broth': {
    id: 'slow-cooked-bone-broth',
    name: 'Slow-Cooked Bone Broth',
    slug: 'slow-cooked-bone-broth',
    shortDescription: 'Slow-simmered chicken bone broth for hydration, joints & gut health.',
    description: 'A slow-simmered golden bone broth crafted from free-range chicken bones, rich in natural collagen, glucosamine, and chondroitin. Perfect as a daily topper, hydration boost, or meal enhancer.',
    keyBenefits: ['Natural collagen for joint health', 'Boosts daily hydration', 'Gentle on sensitive stomachs', 'Zero salt, onion, garlic', '100% human-grade ingredients'],
    ingredients: 'Free-Range Chicken Bones, Filtered Water, Apple Cider Vinegar (trace).',
    nutritionalInfo: { energy: '12 kcal/100ml', crudeProtein: '1.8%', crudeFat: '0.3%', crudeFiber: '0%', moisture: '98%' },
    feedingGuide: [
      { weight: 'Up to 5 kg', daily: '30 – 50 ml/day' },
      { weight: '5 – 15 kg', daily: '50 – 100 ml/day' },
      { weight: '15 – 30 kg', daily: '100 – 150 ml/day' },
      { weight: '30 kg & above', daily: '150 – 200 ml/day' },
    ],
    dietChangeGuide: 'Serve warm or at room temperature as a topper or standalone drink.',
    suitableFor: 'Puppy & Adult Dogs – All Breeds & Sizes',
    isVeg: false,
    foodType: 'BROTH',
    category: { name: 'Broth', slug: 'broth' },
    images: [{ url: '/images/products/golden-chicken-broth-front.jpg', altText: 'Slow-Cooked Bone Broth' }],
    variants: [{ id: 'v-scbb', name: '250ml Pouch', mrp: 149, sellingPrice: 129, stockQuantity: 100 }],
  },
};

async function getProduct(slug) {
  // Always check mock data first — this ensures all locally-defined products work offline
  const mockFallback = MOCK_PRODUCTS[slug];

  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/products/${slug}`,
      { next: { revalidate: 300 } }
    );
    if (res.status === 404) {
      // API doesn't know this slug — use mock if available, otherwise 404
      if (mockFallback) {
        const related = Object.values(MOCK_PRODUCTS).filter((p) => p.slug !== slug);
        return { product: mockFallback, relatedProducts: related.slice(0, 4) };
      }
      return null;
    }
    if (!res.ok) throw new Error('API error');
    const data = await res.json();
    return data;
  } catch {
    // Network / parse error — fall back to mock
    const fallback = mockFallback || MOCK_PRODUCTS['chicken-vegetables'];
    const related = Object.values(MOCK_PRODUCTS).filter((p) => p.slug !== slug);
    return { product: fallback, relatedProducts: related.slice(0, 4) };
  }
}

export async function generateMetadata({ params }) {
  const { slug } = await params;
  const data = await getProduct(slug);
  const product = data?.product;
  if (!product) return { title: 'Product Not Found' };

  return {
    title: product.metaTitle || `${product.name} | Fresh Dog Food`,
    description: product.metaDescription || product.shortDescription,
    openGraph: {
      title: product.name,
      description: product.shortDescription,
      images: product.images?.[0] ? [product.images[0].url] : [],
      type: 'website',
    },
  };
}

export default async function ProductPage({ params }) {
  const { slug } = await params;
  const data = await getProduct(slug);

  if (!data || data === null) notFound();

  const { product, relatedProducts } = data;

  return (
    <>
      {/* Breadcrumb */}
      <div className="bg-white border-b border-plum-900/10 w-full overflow-hidden">
        <div className="container-main py-1.5 sm:py-2">
          <nav className="text-[11px] sm:text-xs text-plum-900/60" aria-label="Breadcrumb">
            <ol className="flex items-center gap-1.5 sm:gap-2 flex-wrap">
              <li><Link href="/" className="hover:text-coral-500 transition-colors">Home</Link></li>
              <li aria-hidden="true" className="text-plum-900/30">/</li>
              <li><Link href="/shop" className="hover:text-coral-500 transition-colors">Shop</Link></li>
              {product.category && (
                <>
                  <li aria-hidden="true" className="text-plum-900/30">/</li>
                  <li>
                    <Link href={`/shop?category=${product.category.slug}`} className="hover:text-coral-500 transition-colors capitalize">
                      {product.category.name}
                    </Link>
                  </li>
                </>
              )}
              <li aria-hidden="true" className="text-plum-900/30">/</li>
              <li className="text-plum-900 font-semibold truncate max-w-[140px] sm:max-w-xs" aria-current="page">{product.name}</li>
            </ol>
          </nav>
        </div>
      </div>

      {/* Product Detail */}
      <ProductDetail product={product} />

      {/* Related Products */}
      {relatedProducts && relatedProducts.length > 0 && (
        <section className="py-10 sm:py-16 bg-[#f0fafb]/40 border-t border-plum-900/10 w-full overflow-hidden" aria-labelledby="related-products-heading">
          <div className="container-main">
            <h2 id="related-products-heading" className="text-xl sm:text-2xl font-extrabold text-plum-900 tracking-tight mb-6 sm:mb-8">
              You Might Also Like
            </h2>
            <ProductGrid products={relatedProducts} />
          </div>
        </section>
      )}
    </>
  );
}
