/**
 * FurBowl Official Product & Recipe Catalog
 * Standardized data for all core meals, curated trial packs, and multi-pack options.
 */

// ─── 5 Core Official Recipes ──────────────────────────────────────────────────
export const CORE_MEALS = [
  {
    id: 'chicken-vegetables',
    slug: 'chicken-vegetables',
    title: 'Chicken & Vegetables Wet Dog Food',
    shortName: 'Chicken & Vegetables',
    isVeg: false,
    about:
      'A nutritious wet dog food made with whole chicken, chicken liver, heart and gizzard, combined with pumpkin, carrot, peas and sweet potato for a wholesome everyday meal.',
    keyIngredients: [
      'Whole Chicken',
      'Chicken Liver',
      'Chicken Heart',
      'Chicken Gizzard',
      'Pumpkin',
      'Carrot',
      'Peas',
      'Sweet Potato',
    ],
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Chicken Gizzard • Pumpkin • Carrot • Peas • Sweet Potato',
    proteinType: 'Chicken (Single Source)',
    tags: ['High Protein', 'Organ Meat', 'Digestive Care'],
    badge: 'Best Seller',
    accentColor: '#fff5f2',
    themeColor: '#ff7a59',
    image: '/images/products/chicken-harvest-front.jpg',
    pouchOnly: '/images/products/only-chicken-harvest-front.jpg',
    dogType: 'Active & Everyday Pups',
  },
  {
    id: 'chicken-rice-vegetables',
    slug: 'chicken-rice-vegetables',
    title: 'Chicken Rice & Vegetables Wet Dog Food',
    shortName: 'Chicken Rice & Veggies',
    isVeg: false,
    about:
      'A wholesome chicken and rice wet dog food made with whole chicken, chicken liver and heart, along with pumpkin, carrot, peas and sweet potato.',
    keyIngredients: [
      'Whole Chicken',
      'Chicken Liver',
      'Chicken Heart',
      'Rice',
      'Pumpkin',
      'Carrot',
      'Peas',
      'Sweet Potato',
    ],
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Rice • Pumpkin • Carrot • Peas • Sweet Potato',
    proteinType: 'Chicken & Rice',
    tags: ['Gentle Carbs', 'Comfort Food', 'Easy Digest'],
    badge: 'Classic Comfort',
    accentColor: '#faf6ed',
    themeColor: '#15aec0',
    image: '/images/products/chicken-homestyle-front.jpg',
    pouchOnly: '/images/products/only-chicken-homestyle-front.jpg',
    dogType: 'Sensitive Stomach Pups',
  },
  {
    id: 'egg-superfood',
    slug: 'egg-superfood',
    title: 'Egg Superfood Wet Dog Food with Quinoa & Vegetables',
    shortName: 'Egg Superfood with Quinoa',
    isVeg: true,
    about:
      'A nutrient-packed egg wet dog food combining egg and quinoa with sweet potato, pumpkin, spinach, carrots, green peas and zucchini for a delicious meal.',
    keyIngredients: [
      'Egg',
      'Quinoa',
      'Sweet Potato',
      'Pumpkin',
      'Carrot',
      'Spinach',
      'Green Peas',
      'Zucchini',
    ],
    highlightIngredients: 'Egg • Quinoa • Sweet Potato • Pumpkin • Carrot • Spinach • Green Peas • Zucchini',
    proteinType: 'Farm Egg & Quinoa',
    tags: ['Superfood', 'Vegetarian Friendly', 'Antioxidant Rich'],
    badge: 'Superfood',
    accentColor: '#f0fafb',
    themeColor: '#0f8e9d',
    image: '/images/products/golden-egg-quinoa-front.jpg',
    pouchOnly: '/images/products/only-golden-egg-quinoa-front.jpg',
    dogType: 'High Energy & Active Pups',
  },
  {
    id: 'paneer-vegetables',
    slug: 'paneer-vegetables',
    title: 'Paneer & Vegetables Wet Dog Food',
    shortName: 'Paneer & Vegetables',
    isVeg: true,
    about:
      'A wholesome vegetarian wet dog food made with paneer, rice and nutritious vegetables including pumpkin, carrot, green peas and spinach.',
    keyIngredients: [
      'Paneer',
      'Rice',
      'Pumpkin',
      'Carrot',
      'Green Peas',
      'Spinach',
      'Chia Seeds',
    ],
    highlightIngredients: 'Paneer • Rice • Pumpkin • Carrot • Green Peas • Spinach • Chia Seeds',
    proteinType: 'Fresh Paneer (100% Veg)',
    tags: ['100% Vegetarian', 'Calcium Rich', 'Gentle Belly'],
    badge: '100% Veg',
    accentColor: '#faf6ed',
    themeColor: '#15aec0',
    image: '/images/products/paneer-greens-front.jpg',
    pouchOnly: '/images/products/only-paneer-greens-front.jpg',
    dogType: 'Vegetarian Households',
  },
  {
    id: 'lamb-lentils',
    slug: 'lamb-lentils',
    title: 'Lamb & Lentils Wet Dog Food with Vegetables',
    shortName: 'Lamb & Lentils',
    isVeg: false,
    about:
      'A hearty lamb wet dog food made with lean lamb meat and lamb liver, combined with red lentils, sweet potato and wholesome vegetables.',
    keyIngredients: [
      'Lean Lamb',
      'Lamb Liver',
      'Red Lentils',
      'Sweet Potato',
      'Carrot',
      'Green Beans',
      'Broccoli',
      'Cauliflower',
    ],
    highlightIngredients: 'Lean Lamb • Lamb Liver • Red Lentils • Sweet Potato • Carrot • Green Beans • Broccoli • Cauliflower',
    proteinType: 'Pasture Lamb & Lentils',
    tags: ['Hypoallergenic', 'Iron Rich', 'Gourmet'],
    badge: 'High Protein',
    accentColor: '#fff5f2',
    themeColor: '#db4d2c',
    image: '/images/products/lamb-lentil-harvest-front.jpg',
    pouchOnly: '/images/products/only-lamb-lentil-harvest-front.jpg',
    dogType: 'Pickiest Eaters & Muscle Building',
  },
];

// ─── Curated Trial Packs ──────────────────────────────────────────────────────
export const TRIAL_PACKS = [
  {
    id: 'all-recipes-trial-pack',
    slug: 'all-recipes-trial-pack',
    title: 'All Recipes Wet Dog Food Trial Pack – 5 x 100g',
    shortName: 'All Recipes Trial Pack',
    packCount: 5,
    pouchWeight: '100g',
    totalWeight: '500g',
    badge: '⭐ Best First Purchase',
    flagship: true,
    price: 499,
    originalPrice: 599,
    discount: '17% OFF',
    purpose: 'Best first-time discovery pack for pups to taste every single recipe.',
    packIngredients: 'Chicken • Lamb • Egg • Paneer • Pumpkin • Carrot',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 1 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 1 },
    ],
    tagline: '5 Flavours • 1 of Each Recipe',
  },
  {
    id: 'chicken-lovers-trial-pack',
    slug: 'chicken-lovers-trial-pack',
    title: 'Chicken Wet Dog Food Trial Pack – 4 x 100g',
    shortName: 'Chicken Lovers Pack',
    packCount: 4,
    pouchWeight: '100g',
    totalWeight: '400g',
    badge: 'Chicken Lovers',
    flagship: false,
    price: 399,
    originalPrice: 479,
    discount: '17% OFF',
    purpose: 'For dogs who prefer classic, irresistible poultry flavours.',
    packIngredients: 'Whole Chicken • Chicken Liver • Pumpkin • Carrot • Green Peas',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 2 },
    ],
    tagline: '2 Chicken Veg + 2 Chicken Rice',
  },
  {
    id: 'meat-lovers-trial-pack',
    slug: 'meat-lovers-trial-pack',
    title: 'Chicken & Lamb Wet Dog Food Trial Pack – 4 x 100g',
    shortName: 'Chicken & Lamb Pack',
    packCount: 4,
    pouchWeight: '100g',
    totalWeight: '400g',
    badge: 'Meat-Focused',
    flagship: false,
    price: 429,
    originalPrice: 519,
    discount: '17% OFF',
    purpose: 'Chicken + lamb combination; more protein-focused positioning.',
    packIngredients: 'Chicken • Lamb • Liver • Pumpkin • Carrot • Red Lentils',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 1 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 2 },
    ],
    tagline: '1 Chicken Veg + 1 Chicken Rice + 2 Lamb',
  },
  {
    id: 'chicken-egg-trial-pack',
    slug: 'chicken-egg-trial-pack',
    title: 'Chicken & Egg Wet Dog Food Trial Pack – 4 x 100g',
    shortName: 'Chicken & Egg Pack',
    packCount: 4,
    pouchWeight: '100g',
    totalWeight: '400g',
    badge: 'Familiar + Variety',
    flagship: false,
    price: 399,
    originalPrice: 479,
    discount: '17% OFF',
    purpose: 'Familiar chicken flavours with superfood egg for variety.',
    packIngredients: 'Chicken • Egg • Pumpkin • Carrot • Green Peas • Quinoa',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 1 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 2 },
    ],
    tagline: '1 Chicken Veg + 1 Chicken Rice + 2 Egg',
  },
  {
    id: 'meat-veggie-variety-pack',
    slug: 'meat-veggie-variety-pack',
    title: 'Meat & Veggie Wet Dog Food Trial Pack – 6 x 100g',
    shortName: 'Meat & Veggie Variety Pack',
    packCount: 6,
    pouchWeight: '100g',
    totalWeight: '600g',
    badge: 'Ultimate Variety',
    flagship: false,
    price: 579,
    originalPrice: 699,
    discount: '17% OFF',
    purpose: 'Complete tasting selection with an extra serving of our #1 Chicken meal.',
    packIngredients: 'Chicken • Lamb • Egg • Paneer • Pumpkin • Carrot',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
    ],
    tagline: '2 Chicken Veg + 1 Chicken Rice + 1 Lamb + 1 Egg + 1 Paneer',
  },
];

// ─── Multi-Pack Sizing Configurations ─────────────────────────────────────────
export const MULTI_PACK_SIZES = [
  {
    count: 4,
    name: '4 Pack',
    title: 'Chicken Dog Food Combo Pack (4 x 100g)',
    subtitle: 'Chicken & Vegetables + Chicken Rice',
    popularFor: 'First taste or weekend trial',
  },
  {
    count: 5,
    name: '5 Pack',
    title: 'All Recipes Dog Food Trial Pack (5 x 100g)',
    subtitle: 'Chicken, Lamb, Egg & Paneer (1 of each)',
    popularFor: 'Most popular discovery pack',
    isFlagship: true,
  },
  {
    count: 6,
    name: '6 Pack',
    title: 'Meat & Veggie Variety Pack (6 x 100g)',
    subtitle: 'Complete tasting with 2x Chicken',
    popularFor: 'Expanded variety trial',
  },
  {
    count: 7,
    name: '7 Pack',
    title: 'All Recipes Dog Food Trial Pack (7 x 100g)',
    subtitle: 'Chicken, Lamb, Egg & Paneer',
    popularFor: '1-Week Fresh Feeding Plan',
  },
  {
    count: 10,
    name: '10 Pack',
    title: 'All Recipes Dog Food Pack (10 x 100g)',
    subtitle: 'Chicken, Lamb, Egg & Paneer',
    popularFor: 'Bi-weekly stock up',
  },
  {
    count: 15,
    name: '15 Pack',
    title: 'All Recipes Dog Food Pack (15 x 100g)',
    subtitle: 'Chicken, Lamb, Egg & Paneer',
    popularFor: 'Half-month fresh meal supply',
  },
  {
    count: 30,
    name: '30 Pack',
    title: 'All Recipes Dog Food Monthly Pack (30 x 100g)',
    subtitle: 'Chicken, Lamb, Egg & Paneer',
    popularFor: 'Monthly full-diet subscription (Best Value)',
  },
];
