/**
 * FurBowl Official Product & Recipe Catalog
 * Standardized data for all core meals, curated trial packs, and multi-pack options.
 */

// ─── 5 Core Official Recipes ──────────────────────────────────────────────────
export const CORE_MEALS = [
  {
    id: 'chicken-vegetables',
    slug: 'chicken-vegetables',
    title: 'Chicken & Vegetables Wet Dog Food',
    shortName: 'Chicken & Vegetables',
    isVeg: false,
    about:
      'A nutritious wet dog food made with whole chicken, chicken liver, heart and gizzard, combined with pumpkin, carrot, peas and sweet potato for a wholesome everyday meal.',
    keyIngredients: [
      'Whole Chicken',
      'Chicken Liver',
      'Chicken Heart',
      'Chicken Gizzard',
      'Pumpkin',
      'Carrot',
      'Peas',
      'Sweet Potato',
    ],
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Chicken Gizzard • Pumpkin • Carrot • Peas • Sweet Potato',
    proteinType: 'Chicken (Single Source)',
    tags: ['High Protein', 'Organ Meat', 'Digestive Care'],
    badge: 'Best Seller',
    accentColor: '#fff5f2',
    themeColor: '#ff7a59',
    image: '/images/products/chicken-harvest-front.jpg',
    pouchOnly: '/images/products/only-chicken-harvest-front.jpg',
    dogType: 'Active & Everyday Pups',
  },
  {
    id: 'chicken-rice-vegetables',
    slug: 'chicken-rice-vegetables',
    title: 'Chicken Rice & Vegetables Wet Dog Food',
    shortName: 'Chicken Rice & Veggies',
    isVeg: false,
    about:
      'A wholesome chicken and rice wet dog food made with whole chicken, chicken liver and heart, along with pumpkin, carrot, peas and sweet potato.',
    keyIngredients: [
      'Whole Chicken',
      'Chicken Liver',
      'Chicken Heart',
      'Rice',
      'Pumpkin',
      'Carrot',
      'Peas',
      'Sweet Potato',
    ],
    highlightIngredients: 'Whole Chicken • Chicken Liver • Chicken Heart • Rice • Pumpkin • Carrot • Peas • Sweet Potato',
    proteinType: 'Chicken & Rice',
    tags: ['Gentle Carbs', 'Comfort Food', 'Easy Digest'],
    badge: 'Classic Comfort',
    accentColor: '#faf6ed',
    themeColor: '#15aec0',
    image: '/images/products/chicken-homestyle-front.jpg',
    pouchOnly: '/images/products/only-chicken-homestyle-front.jpg',
    dogType: 'Sensitive Stomach Pups',
  },
  {
    id: 'egg-superfood',
    slug: 'egg-superfood',
    title: 'Egg Superfood Wet Dog Food with Quinoa & Vegetables',
    shortName: 'Egg Superfood with Quinoa',
    isVeg: true,
    about:
      'A nutrient-packed egg wet dog food combining egg and quinoa with sweet potato, pumpkin, spinach, carrots, green peas and zucchini for a delicious meal.',
    keyIngredients: [
      'Egg',
      'Quinoa',
      'Sweet Potato',
      'Pumpkin',
      'Carrot',
      'Spinach',
      'Green Peas',
      'Zucchini',
    ],
    highlightIngredients: 'Egg • Quinoa • Sweet Potato • Pumpkin • Carrot • Spinach • Green Peas • Zucchini',
    proteinType: 'Farm Egg & Quinoa',
    tags: ['Superfood', 'Vegetarian Friendly', 'Antioxidant Rich'],
    badge: 'Superfood',
    accentColor: '#f0fafb',
    themeColor: '#0f8e9d',
    image: '/images/products/golden-egg-quinoa-front.jpg',
    pouchOnly: '/images/products/only-golden-egg-quinoa-front.jpg',
    dogType: 'High Energy & Active Pups',
  },
  {
    id: 'paneer-vegetables',
    slug: 'paneer-vegetables',
    title: 'Paneer & Vegetables Wet Dog Food',
    shortName: 'Paneer & Vegetables',
    isVeg: true,
    about:
      'A wholesome vegetarian wet dog food made with paneer, rice and nutritious vegetables including pumpkin, carrot, green peas and spinach.',
    keyIngredients: [
      'Paneer',
      'Rice',
      'Pumpkin',
      'Carrot',
      'Green Peas',
      'Spinach',
      'Chia Seeds',
    ],
    highlightIngredients: 'Paneer • Rice • Pumpkin • Carrot • Green Peas • Spinach • Chia Seeds',
    proteinType: 'Fresh Paneer (100% Veg)',
    tags: ['100% Vegetarian', 'Calcium Rich', 'Gentle Belly'],
    badge: '100% Veg',
    accentColor: '#faf6ed',
    themeColor: '#15aec0',
    image: '/images/products/paneer-greens-front.jpg',
    pouchOnly: '/images/products/only-paneer-greens-front.jpg',
    dogType: 'Vegetarian Households',
  },
  {
    id: 'lamb-lentils',
    slug: 'lamb-lentils',
    title: 'Lamb & Lentils Wet Dog Food with Vegetables',
    shortName: 'Lamb & Lentils',
    isVeg: false,
    about:
      'A hearty lamb wet dog food made with lean lamb meat and lamb liver, combined with red lentils, sweet potato and wholesome vegetables.',
    keyIngredients: [
      'Lean Lamb',
      'Lamb Liver',
      'Red Lentils',
      'Sweet Potato',
      'Carrot',
      'Green Beans',
      'Broccoli',
      'Cauliflower',
    ],
    highlightIngredients: 'Lean Lamb • Lamb Liver • Red Lentils • Sweet Potato • Carrot • Green Beans • Broccoli • Cauliflower',
    proteinType: 'Pasture Lamb & Lentils',
    tags: ['Hypoallergenic', 'Iron Rich', 'Gourmet'],
    badge: 'High Protein',
    accentColor: '#fff5f2',
    themeColor: '#db4d2c',
    image: '/images/products/lamb-lentil-harvest-front.jpg',
    pouchOnly: '/images/products/only-lamb-lentil-harvest-front.jpg',
    dogType: 'Pickiest Eaters & Muscle Building',
  },
];

// ─── Curated 7-Day Packs (Multiples of 7, 100g each) ─────────────────────────
export const TRIAL_PACKS = [
  {
    id: 'all-recipes-trial-pack',
    slug: 'all-recipes-trial-pack',
    title: 'All Recipes Wet Dog Food Pack – 7 x 100g',
    shortName: 'All Recipes 7-Day Pack',
    packCount: 7,
    pouchWeight: '100g',
    totalWeight: '700g',
    badge: '⭐ Best 7-Day Discovery',
    flagship: true,
    price: 699,
    originalPrice: 839,
    discount: '17% OFF',
    purpose: 'Complete 7-day tasting discovery pack for pups to taste every single recipe across the week.',
    packIngredients: 'Chicken • Lamb • Egg • Paneer • Pumpkin • Carrot',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 2 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 1 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
    ],
    tagline: '5 Flavours • 7 Pouches (1 Week)',
  },
  {
    id: 'chicken-lovers-trial-pack',
    slug: 'chicken-lovers-trial-pack',
    title: 'Chicken Wet Dog Food Pack – 7 x 100g',
    shortName: 'Chicken Lovers 7-Day Pack',
    packCount: 7,
    pouchWeight: '100g',
    totalWeight: '700g',
    badge: 'Chicken Lovers',
    flagship: false,
    price: 649,
    originalPrice: 779,
    discount: '17% OFF',
    purpose: 'A full 7-day poultry feast for dogs who love classic chicken recipes.',
    packIngredients: 'Whole Chicken • Chicken Liver • Pumpkin • Carrot • Green Peas',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 4 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 3 },
    ],
    tagline: '4 Chicken Veg + 3 Chicken Rice',
  },
  {
    id: 'meat-lovers-trial-pack',
    slug: 'meat-lovers-trial-pack',
    title: 'Chicken & Lamb Wet Dog Food Pack – 7 x 100g',
    shortName: 'Chicken & Lamb 7-Day Pack',
    packCount: 7,
    pouchWeight: '100g',
    totalWeight: '700g',
    badge: 'Meat-Focused',
    flagship: false,
    price: 699,
    originalPrice: 839,
    discount: '17% OFF',
    purpose: '7-day chicken & lamb power pack pairing high protein poultry with rich iron pasture lamb.',
    packIngredients: 'Chicken • Lamb • Liver • Pumpkin • Carrot • Red Lentils',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 2 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 3 },
    ],
    tagline: '2 Chicken Veg + 2 Chicken Rice + 3 Lamb',
  },
  {
    id: 'chicken-egg-trial-pack',
    slug: 'chicken-egg-trial-pack',
    title: 'Chicken & Egg Wet Dog Food Pack – 7 x 100g',
    shortName: 'Chicken & Egg 7-Day Pack',
    packCount: 7,
    pouchWeight: '100g',
    totalWeight: '700g',
    badge: 'Familiar + Variety',
    flagship: false,
    price: 649,
    originalPrice: 779,
    discount: '17% OFF',
    purpose: 'Familiar chicken favourites balanced with superfood farm egg for a week of radiant fur & stamina.',
    packIngredients: 'Chicken • Egg • Pumpkin • Carrot • Green Peas • Quinoa',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 2 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 3 },
    ],
    tagline: '2 Chicken Veg + 2 Chicken Rice + 3 Egg',
  },
  {
    id: 'meat-veggie-variety-pack',
    slug: 'meat-veggie-variety-pack',
    title: 'Meat & Veggie Wet Dog Food Pack – 7 x 100g',
    shortName: 'Meat & Veggie 7-Day Variety',
    packCount: 7,
    pouchWeight: '100g',
    totalWeight: '700g',
    badge: 'Ultimate Variety',
    flagship: false,
    price: 699,
    originalPrice: 839,
    discount: '17% OFF',
    purpose: 'Complete 7-day culinary tasting across all poultry, meat, egg and garden paneer recipes.',
    packIngredients: 'Chicken • Lamb • Egg • Paneer • Pumpkin • Carrot',
    breakdown: [
      { mealId: 'chicken-vegetables', name: 'Chicken & Vegetables', count: 2 },
      { mealId: 'chicken-rice-vegetables', name: 'Chicken Rice with Vegetables', count: 1 },
      { mealId: 'lamb-lentils', name: 'Lamb & Lentils', count: 2 },
      { mealId: 'egg-superfood', name: 'Egg SuperFood', count: 1 },
      { mealId: 'paneer-vegetables', name: 'Paneer Medley', count: 1 },
    ],
    tagline: '2 Chicken Veg + 1 Chicken Rice + 2 Lamb + 1 Egg + 1 Paneer',
  },
];

// ─── Multi-Pack Sizing Configurations (Multiples of 7, 100g each) ─────────────
export const MULTI_PACK_SIZES = [
  {
    count: 7,
    slug: 'plan-pack-of-7',
    name: '7 Pack',
    title: '7-Pack Weekly Fresh Feeding (7 x 100g)',
    subtitle: '1-Week Plan • Chicken, Lamb, Egg & Paneer',
    popularFor: '1-Week Fresh Starter Routine',
    price: 699,
    originalPrice: 839,
    image: '/images/products/bundles/furbowl-bundle-chicken.jpg',
  },
  {
    count: 14,
    slug: 'plan-pack-of-14',
    name: '14 Pack',
    title: '14-Pack Bi-Weekly Fresh Feeding (14 x 100g)',
    subtitle: '2-Week Plan • Rotational Fresh Meals',
    popularFor: '2-Week Habit & Routine Plan',
    isFlagship: true,
    price: 1349,
    originalPrice: 1679,
    image: '/images/products/bundles/furbowl-bundle-all-three.jpg',
  },
  {
    count: 21,
    slug: 'plan-pack-of-21',
    name: '21 Pack',
    title: '21-Pack Three-Week Fresh Feeding (21 x 100g)',
    subtitle: '3-Week Plan • Complete Nutrient Variety',
    popularFor: '3-Week Digestive Transformation',
    price: 1949,
    originalPrice: 2519,
    image: '/images/products/bundles/furbowl-bundle-lamb.jpg',
  },
  {
    count: 28,
    slug: 'plan-pack-of-28',
    name: '28 Pack',
    title: '28-Pack Monthly Fresh Feeding (28 x 100g)',
    subtitle: '4-Week Complete Month • Best Value',
    popularFor: 'Full Month Subscription Routine',
    isFlagship: true,
    price: 2499,
    originalPrice: 3359,
    image: '/images/products/bundles/bundle-all-three.jpg',
  },
];
